title: Home
views:
  - title: Home
    path: home
    badges: []
    cards:
      - type: entities
        title: Entities
        entities:
          - entity: input_boolean.my_switch
          - entity: input_select.fan_speed
  - title: View 1
    path: view_1
    badges: []
    cards:
      - type: markdown
        content: View 1 panel
  - title: View 2
    path: view_2
    badges: []
    cards:
      - type: markdown
        content: View 2 panel