title: Home
views:
  - theme: Backend-selected
    title: Home
    path: home
    badges: []
    cards:
      - type: entities
        title: Entities
        entities:
          - entity: input_boolean.my_switch
          - entity: input_select.fan_speed