overrides:
  ajv@>=7.0.0-alpha.0 <8.18.0: '>=8.18.0'
  minimatch@<3.1.4: '>=3.1.4'
  on-headers@<1.1.0: '>=1.1.0'
  qs@<6.14.2: '>=6.14.2'
  serialize-javascript@<=7.0.2: '>=7.0.3'
  svgo@>=3.0.0 <3.3.3: '>=3.3.3'
  webpack@>=5.49.0 <=5.104.0: '>=5.104.1'
