overrides:
  follow-redirects@<=1.15.11: '>=1.16.0'
  minimatch@<3.1.4: '>=3.1.4'
  on-headers@<1.1.0: '>=1.1.0'
  path-to-regexp@<0.1.13: '>=0.1.13'
  postcss@<8.5.10: '>=8.5.10'
  qs@<6.14.2: '>=6.14.2'
  serialize-javascript@<7.0.5: '>=7.0.5'
  uuid@<14.0.0: '>=14.0.0'
