name: Create release

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set-up Node
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'yarn'
          registry-url: 'https://registry.npmjs.org'
      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "dir=$(yarn cache dir)" >> $GITHUB_OUTPUT
      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: dependencies-v1-${{ runner.os }}-${{ hashFiles('yarn.lock') }}
      - name: Cache Docker images
        uses: ScribeMD/docker-cache@0.3.7
        with:
          key: docker-v1-${{ runner.os }}-${{ hashFiles('.hass/config/.HA_VERSION', '.playwright_docker_version') }}
      - name: Install deps
        run: yarn install --frozen-lockfile
      - name: E2E tests
        run: |
          touch .env
          echo HA_TOKEN=${{ secrets.HA_TOKEN }} >> .env
          yarn test:all
      - name: Create coverage
        run: yarn coverage:report
      - name: Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Build Changelog
        id: build_changelog
        uses: mikepenz/release-changelog-builder-action@v3
        with:
          configurationJson: |
            {
              "categories": [
                {
                  "title": "## 🚀 Features",
                  "labels": ["feature", "feature-request", "enhancement", "request"]
                },
                {
                  "title": "## 🛠 Fixes",
                  "labels": ["fix", "bug"]
                },
                {
                  "title": "## 🧩 Dependencies",
                  "labels": ["dependencies"]
                },
                {
                  "title": "## ⚙️ Configuration",
                  "labels": ["configuration"]
                },
                {
                  "title": "## 📝 Documentation",
                  "labels": ["documentation"]
                },
                {
                  "title": "## 📦 Other",
                  "labels": []
                }
              ],
              "template": "#{{CHANGELOG}}",
              "pr_template": "- #{{TITLE}}\n   - PR: ##{{NUMBER}} by @#{{AUTHOR}}",
              "empty_template": "#{{OWNER}}\n#{{REPO}}\n#{{FROM_TAG}}\n#{{TO_TAG}}",
              "max_pull_requests": 1000,
              "max_back_track_time_days": 1000
            }
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Create a release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            dist/custom-sidebar.js
            dist/custom-sidebar-json.js
            dist/custom-sidebar-yaml.js
          body: |
            ${{ steps.build_changelog.outputs.changelog }}