name: Tests Docs

on:
  pull_request:
    branches:
      - master
    paths:
      - 'docs/**'

jobs:
  tests-docs:
    name: Tests Docs
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Install pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 9
          run_install: false
      - name: Set-up Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'
      - name: Install dependencies
        run: |
          cd docs
          pnpm install
      - name: Build Docs
        run: |
          cd docs
          pnpm build