name: HACS Action

on:
  push:
    branches:
      - master
  pull_request:
  schedule:
    - cron: '0 0 * * *'

jobs:
  hacs:
    name: Validate
    if: ${{ !(github.event_name == 'pull_request' && github.event.pull_request.head.repo.fork) }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: HACS Action
        uses: hacs/action@main
        with:
          category: plugin