name: HACS Action

on:
  push:
    branches:
      - master
  pull_request:
  schedule:
    - cron: '0 0 * * *'

jobs:
  hacs:
    name: Validate
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: HACS Action
        uses: hacs/action@main
        with:
          category: plugin