name: HACS Action

on:
  push:
  pull_request:
  schedule:
    - cron: "0 0 * * *"

jobs:
  hacs:
    name: HACS Action
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v3"
      - if: github.repository == 'elchininet/custom-sidebar'
        name: HACS Action
        uses: "hacs/action@main"
        with:
          category: "plugin"