name: Test

on:
  push:
    branches:
      - master
  pull_request:

jobs:      
  test:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'yarn'
      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "dir=$(yarn cache dir)" >> $GITHUB_OUTPUT
      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: dependencies-v1-${{ runner.os }}-${{ hashFiles('yarn.lock') }}
      - name: Install
        run: yarn install --frozen-lockfile
      - name: E2E tests
        run: |
          touch .env
          echo HA_TOKEN=${{ secrets.HA_TOKEN }} >> .env
          yarn test:all
      - name: Create coverage
        run: yarn coverage:report
      - name: Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}